Issue junki
DEU-hanium/.github pull request #9
Opened 2023-08-10 09:51 UTC by junki1912

Docs: link 추가 및 파일 경로 변경

2023-08-10 13:32 UTC, leemhoon00 requested changes
수정요청

2023-08-10 13:32 UTC, leemhoon00 commented on profile/visualization_kibana/visualizion_kibana.md
> +```
코드블럭 마땅한 언어가 없으면 json이라도 설정해주세용

2023-08-10 13:32 UTC, leemhoon00 commented on profile/README.md
> +- [OpenSearch에 적재된 로그 데이터를 통해 악성 크롤링 탐지하기](https://github.com/DEU-hanium/detect_crawling/blob/master/README.md)
.github 레포 외에 다른 레포 readme는 안받습니다
이 부분은 원래꺼로 수정바람

2023-08-11 00:54 UTC, junki1912 commented on profile/README.md
> +- [OpenSearch에 적재된 로그 데이터를 통해 악성 크롤링 탐지하기](https://github.com/DEU-hanium/detect_crawling/blob/master/README.md)
최대한 빨리 수정하겠습니다

2023-08-13 09:19 UTC, closed without merging